version: "3.8"

services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - user-service
      - job-service
      - application-service
      - recommend-service

  user-service:
    build:
      context: ./user-service
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./user-service:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh

  job-service:
    build:
      context: ./job-service
      dockerfile: dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./job-service:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh

  application-service:
    build:
      context: ./application-service
      dockerfile: dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./application-service:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh

  recommend-service:
    build:
      context: ./recommend-service
      dockerfile: dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./recommend-service:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh
